# Generated by Django 4.1.1 on 2022-11-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.DeleteModel(
            name='depart',
        ),
        migrations.DeleteModel(
            name='role',
        ),
    ]
